spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clubs?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret-key: "U3VwZXJTZWNyZXRLZXlGb3JITUFDMjU2"
  refresh-secret-key: "UmVmcmVzaFNlY3JldEtleUZvckhTQTI1Ng=="
  access-token-expiration: 900000  # 15분 (밀리초)
  refresh-token-expiration: 604800000  # 7일 (밀리초)
